program: trainer.py
method: bayes
metric:
  goal: minimize
  name: Relative Time (Process)
parameters:
  scheduler_gamma:
    max: 1.9371857791644504
    min: 0.255292226700994
    distribution: uniform
  weight_decay:
    max: 0.026251475866129644
    min: 0.002963610512041071
    distribution: uniform
  batch_size:
    max: 1992
    min: 40
    distribution: int_uniform
  early_stopping_patience:
    max: 10
    min: 1
    distribution: int_uniform
  learning_rate:
    max: 0.0036677300773324097
    min: 0.0004767494294738798
    distribution: uniform
  optimizer:
    values:
      - Adam
    distribution: categorical
  early_stopping_delta:
    max: 0.000031609734803264745
    min: 0.000003975410340591648
    distribution: uniform
  scheduler_step_size:
    max: 4
    min: 1
    distribution: int_uniform
  scheduler:
    values:
      - StepLR
    distribution: categorical
  epochs:
    values: [10, 20, 30]
