_name:
    value: wandb.config
_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 1
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 64
learning_rate:
    value: 0.06697728766802258
optimizer:
    value: SGD
scheduler:
    value: StepLR
step_size:
    value: 22
weight_decay:
    value: 7.677453602367855e-05
